version: '6.2'
services:
  cache:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  suggest:
    build: .
    ports:
      - "5000:5000"
volumes:
  cache:
    driver: local